version: "3.6"
services:

  recosante_exporter:
    container_name: recosante_exporter
    image: quay.io/prometheuscommunity/json-exporter
    restart: unless-stopped
    ports:
      - "7979:7979"
    volumes:
      - ../config.yml:/config.yml

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/recosante_dashboard.json
    volumes:
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/recosante.yml
      - ./grafana-dashboard.json:/var/lib/grafana/dashboards/recosante_dashboard.json
