version: "3.6"
services:

  recosante_exporter:
    container_name: recosante_exporter
    image: quay.io/prometheuscommunity/json-exporter
    restart: unless-stopped
    ports:
      - "7979:7979"
    volumes:
      - ../config.yml:/config.yml

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
