{
 "title": "Recosanté",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Tuiles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Qualité de l'air",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "recosante_atmo_global_index_value",
     "legendFormat": "{{ label }}"
    }
   ]
  },
  {
   "title": "Qualité de l'air",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "recosante_atmo_index_value", "legendFormat": "{{ label }}" }
   ]
  },
  {
   "title": "Pollens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "recosante_raep_global_index_value",
     "legendFormat": "{{ label }}"
    }
   ]
  },
  {
   "title": "Radon",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "recosante_radon_global_index_value",
     "legendFormat": "{{ label }}"
    }
   ]
  },
  { "title": "Jauges", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Qualité de l'air",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "recosante_atmo_global_index_value",
     "legendFormat": "{{ label }}"
    }
   ]
  },
  {
   "title": "Qualité de l'air",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "recosante_atmo_index_value", "legendFormat": "{{ label }}" }
   ]
  },
  {
   "title": "Pollens",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "recosante_raep_global_index_value",
     "legendFormat": "{{ label }}"
    }
   ]
  },
  {
   "title": "Radon",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "recosante_radon_global_index_value",
     "legendFormat": "{{ label }}"
    }
   ]
  },
  { "title": "Graphiques", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Pollens",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "recosante_raep_index_value", "legendFormat": "{{ label }}" }
   ]
  },
  {
   "title": "Particules",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "recosante_atmo_index_value", "legendFormat": "{{ label }}" }
   ]
  }
 ]
}